version: "3.8"

services:
  # nginx:
  #   image: "nginx:stable-alpine"
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./src:/var/www/laravel
  #   depends_on:
  #     - mysql
  #     - php
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    ports:
      - "8000:8000"
    command:
      - php
      - artisan
      - serve
      - --host
      - 0.0.0.0
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan:
    build: 
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
      - './src/storage/app/public:/var/www/laravel/public/storage'
      - './src/public:/var/www/laravel/public'
    entrypoint: ["php", "/var/www/laravel/artisan"]

  # node:
  #   build: 
  #     context: dockerfiles
  #     dockerfile: node.Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./src:/var/www/laravel