version: "3.8"

services:
  laravel:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/laravel
    ports:
      - "8000:8000"
      - "5173:5173"
    command:
      - composer
      - run
      - dev 
      
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env

